### ISSUE TITLE
not work and blocked everything to execute 

### ISSUE THREAD

**Issue by alirezaimi** [Aasim-A/AsyncTimer#15] opened 2022-01-29 17:02 UTC
Hi
I use just an example of this library and everything blocked ! why ?!

**Comment by Aasim-A** [comment] 2022-01-29 19:13
What board have you used?
And what do you mean everything got blocked?

**Comment by alirezaimi** [comment] 2022-01-30 08:01
I'm using esp8266,esp01 and nodemcu , 
I want to my buzzer make sound separated from other loop function parts, but this library block whole loop from buzzing and then continue when buzzing completed. 
The whole idea of this library is working perfectly and part of my code run in periodic intervals, but i want run part of my code asynchronously and can't work it out !

**Comment by Aasim-A** [comment] 2022-01-30 09:54
can you provide the code you've used?

**Comment by alirezaimi** [comment] 2022-01-30 12:52
@Aasim-A 
This is all my code ! :
https://docs.google.com/document/d/1qWTXvV5RjBV4b1ESOgxf1ojZNUjIHhma8EaoMFfqg00/edit?usp=sharing

**Comment by Aasim-A** [comment] 2022-01-30 15:28
wow that's a lot of code to go through, can you give a brief example to reproduce the issue?

**Comment by alexandermcpherson** [comment] 2022-01-31 14:13
@alirezaimi maybe I am being stupid but you are blocking executing by calling delay() a lot, replace delay for t.setTimeout().. but keep count of how many you use it. When I init AsyncTimer I use AsyncTimer t(89); thats how many times I am using it as an example if you are using it more than 10 you need to provide the init with a value as above otherwise its safe to ommit it.

**Comment by Aasim-A** [comment] 2022-01-31 20:34
@alexandermcpherson Hi mate, just want to clarify that the number to initialise is not calculated after how many times you call `setTimeout` or `setInterval`, rather, this number represents how many slots are available to be occupied by either `setTimeout` or `setInterval`, once `setTimeout` is triggered, its slot gets cleared and can be occupied by another call, so this number is determined by the max number of simultaneous calls you have.
I hope that's cleared things up

**Comment by Aasim-A** [comment] 2022-01-31 20:41
> you are blocking executing by calling delay() a lot, replace delay for t.setTimeout()

I agree, any `delay` call blocks the timer and messes up its calls, if you can post a brief example using `delay`, we could rewrite it to use `AsymcTimer` to make things easier.

**Comment by alexandermcpherson** [comment] 2022-01-31 20:46
@Aasim-A yeah that's clear nice one 👍

**Comment by Aasim-A** [comment] 2022-02-20 10:20
Since no further response was received, I'll close this issue, if you want your code to be async, you must not use the `delay` method because it messes up everything

**Closed by Aasim-A** 2022-02-20 10:20 UTC
